services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
    - 9000:9000
    - 9001:9001 
    volumes:
      - ./docker-dev-volumes/minio/data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
  fe:
    build:
      context: . 
      dockerfile: Dockerfile-fe-dev 
    volumes:
        - ./fe:/app
        - /app/node_modules
    tty: true
    ports:
      - 81:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:82/api
      - NODE_ENV=development 
      - WATCHPACK_POLLING=true
    command: ["yarn","start"]
  be:
    build: 
      context: . 
      dockerfile: Dockerfile-be-dev
    ports:
      - 82:80
    volumes:
      - ./be:/var/www
      - ./be/public:/var/www/html